def pageHandler(win):
    if win.page == 1:
        win.page_num.setText("1/4")
        win.page_num.move(280, 5)

        win.backButton.move(50, 275)
        win.nextButton.move(175, 275)

        win.setGeometry(win.x(), win.y(), 300, 300)

        win.redhp.setVisible(False)
        win.redhp_input.setVisible(False)
        win.fullredhp.setVisible(False)
        win.fullredhp_input.setVisible(False)
        win.soul_hearts.setVisible(False)
        win.soul_hearts_input.setVisible(False)
        win.black_hearts.setVisible(False)
        win.black_hearts_input.setVisible(False)
        win.coins.setVisible(False)
        win.coins_input.setVisible(False)
        win.hp_desc.setVisible(False)
        win.all_items_layout.setVisible(False)
        win.all_items_label.setVisible(False)
        win.added_items_label.setVisible(False)
        win.added_items_layout.setVisible(False)
        win.add_item.setVisible(False)
        win.remove_item.setVisible(False)

        win.challenge_name.setVisible(True)
        win.challenge_name_input.setVisible(True)
        win.character.setVisible(True)
        win.character_input.setVisible(True)
        win.end_boss.setVisible(True)
        win.end_boss_input.setVisible(True)
        win.altPath.setVisible(True)
        win.blindfolded.setVisible(True)
        win.hard_mode.setVisible(True)
    elif win.page == 2:
        win.page_num.move(280, 5)
        win.page_num.setText("2/4")

        win.backButton.move(50, 275)
        win.nextButton.move(175, 275)

        win.setGeometry(win.x(), win.y(), 300, 300)

        win.challenge_name.setVisible(False)
        win.challenge_name_input.setVisible(False)
        win.character.setVisible(False)
        win.character_input.setVisible(False)
        win.end_boss.setVisible(False)
        win.end_boss_input.setVisible(False)
        win.altPath.setVisible(False)
        win.blindfolded.setVisible(False)
        win.hard_mode.setVisible(False)
        win.all_items_label.setVisible(False)
        win.all_items_layout.setVisible(False)
        win.added_items_label.setVisible(False)
        win.added_items_layout.setVisible(False)
        win.add_item.setVisible(False)
        win.remove_item.setVisible(False)

        win.redhp.setVisible(True)
        win.redhp_input.setVisible(True)
        win.fullredhp.setVisible(True)
        win.fullredhp_input.setVisible(True)
        win.soul_hearts.setVisible(True)
        win.soul_hearts_input.setVisible(True)
        win.black_hearts.setVisible(True)
        win.black_hearts_input.setVisible(True)
        win.coins.setVisible(True)
        win.coins_input.setVisible(True)
        win.hp_desc.setVisible(True)
    elif win.page == 3:
        win.setGeometry(win.x(), win.y(), 500, 300)

        win.backButton.move(155, 275)
        win.nextButton.move(275, 275)

        win.page_num.setText("3/4")
        win.page_num.move(480, 5)

        win.redhp.setVisible(False)
        win.redhp_input.setVisible(False)
        win.fullredhp.setVisible(False)
        win.fullredhp_input.setVisible(False)
        win.soul_hearts.setVisible(False)
        win.soul_hearts_input.setVisible(False)
        win.black_hearts.setVisible(False)
        win.black_hearts_input.setVisible(False)
        win.coins.setVisible(False)
        win.coins_input.setVisible(False)
        win.hp_desc.setVisible(False)

        win.all_items_label.setVisible(True)
        win.all_items_layout.setVisible(True)
        win.added_items_label.setVisible(True)
        win.added_items_layout.setVisible(True)
        win.add_item.setVisible(True)
        win.remove_item.setVisible(True)
        win.backButton.setVisible(True)
    elif win.page == 4:
        win.page_num.setText("4/4")
        win.page_num.move(280, 5)
        win.backButton.setVisible(False)
        win.nextButton.setVisible(False)
