lua = """-- generated by C_ffeeStain's Custom Challenge Generator

local tboi_mod = RegisterMod("{}", 1)
local challenge_id = {}


local function smelt(trinket_id)
	local plr = Isaac:GetPlayer()
	plr:AddTrinket(trinket_id, true)
	plr:UseActiveItem(479, false)
end

if Isaac:GetChallenge() == challenge_id then
{}
end
"""


def generate_file(trinket_ids, challenge_id, challenge_name):
    return lua.format(
        challenge_name,
        challenge_id,
        "\n".join(["    smelt({})".format(trinket_id) for trinket_id in trinket_ids]),
    )


if __name__ == "__main__":
    print(generate_file([1, 2, 3, 4], 1, "Test"))
